-- Run in Supabase SQL editor

create table if not exists public.arena_votes (
  id bigint generated by default as identity primary key,
  room text not null,
  name text not null,
  vote text not null check (vote in ('A', 'B', 'tie')),
  confidence int not null check (confidence between 1 and 5),
  rationale text not null,
  created_at timestamptz not null default now()
);

create index if not exists arena_votes_room_created_idx
  on public.arena_votes (room, created_at desc);

alter table public.arena_votes enable row level security;

-- Server route uses service role key, so no public policies required.
-- Optional read policy for anon users:
-- create policy "anon read arena votes"
-- on public.arena_votes for select
-- to anon
-- using (true);

